# -*- coding: utf-8 -*-
"""Python_Quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10h0fmho9LiN8SunW8UcbsVKpKSAzP1zD
"""

score = 4
print("Hello !! Welcome to Quiz Game !!")
name = input("Enter your name: ")

print("\nYou score 1 mark per question")
print("Enter the number of the correct answer")

try:
  question_1 = int(input("\nQ1] How many continents in the world? \n1] 5 \n2] 6 \n3] 7 \n4] 8\n"))
  if question_1 == 3:
    print("You are correct")
  else:
    print("Incorrect Answer")
    score -= 1


  question_2 = int(input("\nQ2] What is the most spoken language in the world? \n1] English \n2] Manderin Chinese \n3] Russian \n4] Spanish \n"))
  if question_2 == 2:
    print("You are correct")
  else:
    print("Incorrect Answer")
    score -= 1

  question_3 = input("\nQ3] What is the answer of 2 + 3 * 5? \n1] 17 \n2] 25 \n3] 10 \n4] 16\n" )
  if question_3 == 1:
    print("You are correct")
  else:
    print("Incorrect Answer")
    score -= 1

 question_4 = input("\nQ3] What is the sign for modulus in python? \n1] / \n2] # \n3] * \n4] %\n" )
  if question_4 == 4:
    print("You are correct")
  else:
    print("Incorrect Answer")
    score -= 1

  print("\n---Score Board---")
  print("Name: ",name)
  print("Final Score: ",score)
  if score == 1:
    print("Good Job!!")
  elif score == 2:
    print("Well done!!")
  elif score == 3:
    print("Excellent!!")
  elif score == 4:
    print("WOOWW!! Excellent work!!)
  else:
    print("Try better next time..")

except ValueError:
  print("Invalid input")
